server:
    port: 8080

spring:
    application:
      name: tlias-backend
    datasource:
      url: jdbc:mysql://localhost:3306/tlias_db?serverTimezone=UTC&useSSL=false
      username: root
      password: Zk48658345@1996
      driver-class-name: com.mysql.cj.jdbc.Driver
      # HikariCP connection pool settings
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        connection-timeout: 30000
        max-lifetime: 1800000

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.kezhang.tlias.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # Use StdOutImpl for logging SQL statements